version: '3.9'
services:
  frontend:
    build: .
    volumes:
      - /app/node_modules
      - /farmer_ordering_fronted:/app
    ports:
      - "5000:5000"
volumes:
  data:
networks:
  shared-network: